# Generated by Django 5.0 on 2023-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.CharField(help_text='Напишите текст, по которому сгенерируется картинка', max_length=150, verbose_name='текст для создания картинки'),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
