# Generated by Django 5.0 on 2023-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createImage', '0002_alter_image_text_delete_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
    ]
